name = input("请输入姓名")
gender = input("请输入性别")
phone = input("请输入电话号码")
addr = input("请输入家庭地址")
email = input("请输入邮箱号码")
print('*'*50)
print("姓名%s\n性别%s\n电话号码%s\n家庭地址%s\n邮箱%s\n"%(name,gender,phone,addr,email))
print('*'*50)
