name = input("请输入您的姓名")
age = input("请输入您的年龄")
sexy = input("请输入您的性别")
high = input("请输入您的身高")
weight = input("请输入体重")
ID_namber = input("请输入身份证号")
education = input("请输入您的学历")
birthday = input("请输入您的出身年月")
amazy = input("请输入您老婆的名字")
addr = input("请输入您的家庭地址")
tel = input("请输入您的电话号码")
case = input("请输入职位")
money = input("请输入薪水")
print('*'*10)
print("姓名%s\n年龄%s\n性别%s\n身高%s\n体重%s\n身份证号%s\n学历%s\n出身年月%s\n老婆的名字%s\n家庭地址%s\n电话号吗%s\n职位%s\n薪水%s\n"%(name,age,sexy,high,weight,ID_namber,education,birthday,amazy,addr,tel,case,money))

